//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2026 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// This package imports things required by build scripts, to force `go mod` to see them as dependencies

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppClass) DeepCopyInto(out *AppClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppClass.
func (in *AppClass) DeepCopy() *AppClass {
	if in == nil {
		return nil
	}
	out := new(AppClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppClassList) DeepCopyInto(out *AppClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]AppClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppClassList.
func (in *AppClassList) DeepCopy() *AppClassList {
	if in == nil {
		return nil
	}
	out := new(AppClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *AppClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppClassSpec) DeepCopyInto(out *AppClassSpec) {
	*out = *in
	if in.PropertyDefinition != nil {
		in, out := &in.PropertyDefinition, &out.PropertyDefinition
		*out = new(PropertyDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.ExplicitDefinition != nil {
		in, out := &in.ExplicitDefinition, &out.ExplicitDefinition
		*out = new(ExplicitDefinition)
		(*in).DeepCopyInto(*out)
	}
	if in.Predicates != nil {
		in, out := &in.Predicates, &out.Predicates
		*out = make([]Predicate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ApplicationClasses != nil {
		in, out := &in.ApplicationClasses, &out.ApplicationClasses
		*out = make([]ApplicationClassSpecEntry, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GlobalClassification != nil {
		in, out := &in.GlobalClassification, &out.GlobalClassification
		*out = new(GlobalSpecClassificationDescriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppClassSpec.
func (in *AppClassSpec) DeepCopy() *AppClassSpec {
	if in == nil {
		return nil
	}
	out := new(AppClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppClassStatus) DeepCopyInto(out *AppClassStatus) {
	*out = *in
	if in.ApplicationClasses != nil {
		in, out := &in.ApplicationClasses, &out.ApplicationClasses
		*out = make([]ApplicationClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.GlobalClassification != nil {
		in, out := &in.GlobalClassification, &out.GlobalClassification
		*out = new(GlobalClassificationDescriptor)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppClassStatus.
func (in *AppClassStatus) DeepCopy() *AppClassStatus {
	if in == nil {
		return nil
	}
	out := new(AppClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppGroupWorkloadReference) DeepCopyInto(out *AppGroupWorkloadReference) {
	*out = *in
	if in.AppGroupWorkloads != nil {
		in, out := &in.AppGroupWorkloads, &out.AppGroupWorkloads
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppGroupWorkloadReference.
func (in *AppGroupWorkloadReference) DeepCopy() *AppGroupWorkloadReference {
	if in == nil {
		return nil
	}
	out := new(AppGroupWorkloadReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *AppInfoReference) DeepCopyInto(out *AppInfoReference) {
	*out = *in
	if in.AppGroupWorkloads != nil {
		in, out := &in.AppGroupWorkloads, &out.AppGroupWorkloads
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new AppInfoReference.
func (in *AppInfoReference) DeepCopy() *AppInfoReference {
	if in == nil {
		return nil
	}
	out := new(AppInfoReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationClass) DeepCopyInto(out *ApplicationClass) {
	*out = *in
	if in.InGroup != nil {
		in, out := &in.InGroup, &out.InGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutGroup != nil {
		in, out := &in.OutGroup, &out.OutGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AppInfos != nil {
		in, out := &in.AppInfos, &out.AppInfos
		*out = make([]AppInfoReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationClass.
func (in *ApplicationClass) DeepCopy() *ApplicationClass {
	if in == nil {
		return nil
	}
	out := new(ApplicationClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ApplicationClassSpecEntry) DeepCopyInto(out *ApplicationClassSpecEntry) {
	*out = *in
	if in.InGroup != nil {
		in, out := &in.InGroup, &out.InGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.OutGroup != nil {
		in, out := &in.OutGroup, &out.OutGroup
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.AppGroupWorkloads != nil {
		in, out := &in.AppGroupWorkloads, &out.AppGroupWorkloads
		*out = make([]AppGroupWorkloadReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ApplicationClassSpecEntry.
func (in *ApplicationClassSpecEntry) DeepCopy() *ApplicationClassSpecEntry {
	if in == nil {
		return nil
	}
	out := new(ApplicationClassSpecEntry)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ClassDef) DeepCopyInto(out *ClassDef) {
	*out = *in
	if in.Clauses != nil {
		in, out := &in.Clauses, &out.Clauses
		*out = make([]ExplicitClause, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ClassDef.
func (in *ClassDef) DeepCopy() *ClassDef {
	if in == nil {
		return nil
	}
	out := new(ClassDef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Clause) DeepCopyInto(out *Clause) {
	*out = *in
	if in.AndClauses != nil {
		in, out := &in.AndClauses, &out.AndClauses
		*out = make([]CondNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Clause.
func (in *Clause) DeepCopy() *Clause {
	if in == nil {
		return nil
	}
	out := new(Clause)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CondNode) DeepCopyInto(out *CondNode) {
	*out = *in
	if in.Left != nil {
		in, out := &in.Left, &out.Left
		*out = new(Condition)
		(*in).DeepCopyInto(*out)
	}
	if in.Right != nil {
		in, out := &in.Right, &out.Right
		*out = new(Condition)
		(*in).DeepCopyInto(*out)
	}
	if in.Rel != nil {
		in, out := &in.Rel, &out.Rel
		*out = new(RelCondition)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CondNode.
func (in *CondNode) DeepCopy() *CondNode {
	if in == nil {
		return nil
	}
	out := new(CondNode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Condition) DeepCopyInto(out *Condition) {
	*out = *in
	if in.Rel != nil {
		in, out := &in.Rel, &out.Rel
		*out = new(RelCondition)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Condition.
func (in *Condition) DeepCopy() *Condition {
	if in == nil {
		return nil
	}
	out := new(Condition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExplicitClause) DeepCopyInto(out *ExplicitClause) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]ExplicitCondition, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExplicitClause.
func (in *ExplicitClause) DeepCopy() *ExplicitClause {
	if in == nil {
		return nil
	}
	out := new(ExplicitClause)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExplicitCondition) DeepCopyInto(out *ExplicitCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExplicitCondition.
func (in *ExplicitCondition) DeepCopy() *ExplicitCondition {
	if in == nil {
		return nil
	}
	out := new(ExplicitCondition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExplicitDefinition) DeepCopyInto(out *ExplicitDefinition) {
	*out = *in
	if in.ClassDefs != nil {
		in, out := &in.ClassDefs, &out.ClassDefs
		*out = make([]ClassDef, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExplicitDefinition.
func (in *ExplicitDefinition) DeepCopy() *ExplicitDefinition {
	if in == nil {
		return nil
	}
	out := new(ExplicitDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalAppGroupClassification) DeepCopyInto(out *GlobalAppGroupClassification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalAppGroupClassification.
func (in *GlobalAppGroupClassification) DeepCopy() *GlobalAppGroupClassification {
	if in == nil {
		return nil
	}
	out := new(GlobalAppGroupClassification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalClassificationDescriptor) DeepCopyInto(out *GlobalClassificationDescriptor) {
	*out = *in
	if in.AppGroups != nil {
		in, out := &in.AppGroups, &out.AppGroups
		*out = make([]GlobalAppGroupClassification, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalClassificationDescriptor.
func (in *GlobalClassificationDescriptor) DeepCopy() *GlobalClassificationDescriptor {
	if in == nil {
		return nil
	}
	out := new(GlobalClassificationDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpecAppGroupClassification) DeepCopyInto(out *GlobalSpecAppGroupClassification) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpecAppGroupClassification.
func (in *GlobalSpecAppGroupClassification) DeepCopy() *GlobalSpecAppGroupClassification {
	if in == nil {
		return nil
	}
	out := new(GlobalSpecAppGroupClassification)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *GlobalSpecClassificationDescriptor) DeepCopyInto(out *GlobalSpecClassificationDescriptor) {
	*out = *in
	if in.AppGroups != nil {
		in, out := &in.AppGroups, &out.AppGroups
		*out = make([]GlobalSpecAppGroupClassification, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new GlobalSpecClassificationDescriptor.
func (in *GlobalSpecClassificationDescriptor) DeepCopy() *GlobalSpecClassificationDescriptor {
	if in == nil {
		return nil
	}
	out := new(GlobalSpecClassificationDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Predicate) DeepCopyInto(out *Predicate) {
	*out = *in
	if in.Clauses != nil {
		in, out := &in.Clauses, &out.Clauses
		*out = make([]Clause, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Predicate.
func (in *Predicate) DeepCopy() *Predicate {
	if in == nil {
		return nil
	}
	out := new(Predicate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *PropertyDefinition) DeepCopyInto(out *PropertyDefinition) {
	*out = *in
	if in.AppInfoProperties != nil {
		in, out := &in.AppInfoProperties, &out.AppInfoProperties
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new PropertyDefinition.
func (in *PropertyDefinition) DeepCopy() *PropertyDefinition {
	if in == nil {
		return nil
	}
	out := new(PropertyDefinition)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RelCondition) DeepCopyInto(out *RelCondition) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RelCondition.
func (in *RelCondition) DeepCopy() *RelCondition {
	if in == nil {
		return nil
	}
	out := new(RelCondition)
	in.DeepCopyInto(out)
	return out
}
